tap "adoptopenjdk/openjdk"
tap "caskroom/cask"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "ant"
brew "python"
brew "awscli"
brew "docker"
brew "fish"
brew "git"
brew "hub"
brew "llvm"
brew "mas"
brew "maven"
brew "node"
brew "netlify-cli"
brew "pipenv"
brew "spim"
brew "yarn"
brew "heroku/brew/heroku"
cask "adoptopenjdk11"
cask "anaconda"
cask "balance-lock"
cask "bartender"
cask "discord"
cask "docker"
cask "duet"
cask "firefox"
cask "google-chrome"
cask "gpg-suite"
cask "jetbrains-toolbox"
cask "kap"
cask "keepassxc"
cask "league-of-legends"
cask "minecraft"
cask "mission-control-plus"
cask "mosaic"
cask "postgres"
cask "postman"
cask "scroll-reverser"
cask "sf-symbols"
cask "sketch"
cask "skype"
cask "steam"
cask "studio-3t"
cask "visual-studio-code"
cask "zoomus"
mas "DaisyDisk", id: 411643860
mas "Deliveries", id: 924726344
mas "Fantastical", id: 975937182
mas "Lungo", id: 1263070803
mas "Master Password", id: 662763204
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
